### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by martinosmartinos** [pods-framework/pods-jobs-queue#3] opened 2015-05-11 14:02 UTC
When installed on wordpress 4.2.2 I get a database error while accessing pods job queue page from the menu (wp-admin/admin.php?page=pods-jobs-queue) :
"Database Error; SQL: SELECT DISTINCT \* FROM `wp_podsjobs` AS `t` ORDER BY `Array` DESC LIMIT 0, 25; Response: Unknown column 'Array' in 'order clause'"

**Comment by sc0ttkclark** [comment] 2015-05-11 14:09
Sorry, this plugin isn't quite ready for prime time, I have actually started a refactor of it to handle more types of jobs, not just we linear queued jobs. I'll reply here with a link when it's ready. I'll also be releasing it on wordpress.org

**Comment by renegademarketer** [comment] 2021-03-04 00:42
What is the status of this script? Especially with PODS 2.8 under development.

**Comment by sc0ttkclark** [comment] 2021-03-04 03:02
This should still be working, I’ve used it on modern WP/Pods projects that still are in production.

**Comment by sc0ttkclark** [comment] 2021-03-04 03:43
I should note that the site it was for wasn’t a fresh install so I may have fixed something that wasn’t fixed in the install code. I’ll look at this with fresh eyes again if possible this weekend.

**Comment by sc0ttkclark** [comment] 2021-03-04 04:15
I can't reproduce the original SQL error so it may have been already fixed a while back.

Anyways, there's a new release sitting at: https://github.com/pods-framework/pods-jobs-queue/releases/tag/0.1.7

**Closed as completed by sc0ttkclark** 2021-03-04 04:15 UTC
Labels: bug
